server:
  port: 11000
spring:
  application:
    name: account-select
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.75.128:3306/basis
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.chen.springCloudSelect.pojo 
test:
  name: chentao-is-you-baba
  
  
