server:
  port: ${port:9091}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.32.166:3306/basis
      username: root
      password: 123456
  application:
  #应用名
    name: user-service
mybatis:
  type-aliases-package: com.chen.springCloudConfig.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10080/eureka
instance:
  创建完user-dev.yml配置文件之后，gitee中的仓库如下：
  3.3. 搭建配置中心微服务
  ip-address: 127.0.0.1
  prefer-ip-address: true
  lease-expiration-duration-in-seconds: 90
  lease-renewal-interval-in-seconds: 30